# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Macontrol < Formula
  desc "Control your Mac from Telegram — system, media, network, power, and more."
  homepage "https://github.com/amiwrpremium/macontrol"
  version "0.2.2"
  license "MIT"

  depends_on "blueutil"
  depends_on "brightness"
  depends_on "imagesnap"
  depends_on "smctemp"
  depends_on "terminal-notifier"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/amiwrpremium/macontrol/releases/download/v0.2.2/macontrol_0.2.2_darwin_arm64.tar.gz"
    sha256 "73cf57f1b10a3dd1c1183a46425393f67e6fb28491cea100f766d35bec13fb8e"

    define_method(:install) do
      bin.install "macontrol"
      (prefix/"launchd").install "launchd/com.amiwrpremium.macontrol.plist"
      (prefix/"sudoers.d").install "sudoers.d/macontrol.sample"
    end
  end

  def caveats
    <<~EOS
      macontrol needs first-run configuration. Run:

        macontrol setup

      Start at login:

        brew services start macontrol

      Some commands need passwordless sudo for a narrow set of binaries
      (shutdown, pmset, wdutil, powermetrics, systemsetup). The setup
      wizard can install /etc/sudoers.d/macontrol for you.
    EOS
  end

  service do
    run [opt_bin/"macontrol", "run", "--log-level=info"]
    keep_alive true
    log_path "#{Dir.home}/Library/Logs/macontrol/macontrol.log"
    error_log_path "#{Dir.home}/Library/Logs/macontrol/macontrol.err.log"
    working_dir HOMEBREW_PREFIX
    environment_variables PATH: std_service_path_env
  end
end
