# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shellboto < Formula
  desc "Telegram bot that gives whitelisted users a live bash shell on the VPS"
  homepage "https://github.com/amiwrpremium/shellboto"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amiwrpremium/shellboto/releases/download/v0.1.3/shellboto_0.1.3_darwin_x86_64.tar.gz"
      sha256 "25127e8c0fe736744d648988c25d2479a03df5258bba9b28d4548d0c8ac48527"

      define_method(:install) do
        bin.install "shellboto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amiwrpremium/shellboto/releases/download/v0.1.3/shellboto_0.1.3_darwin_arm64.tar.gz"
      sha256 "4e3b850e16c25b885c8640c21ae60e83eeca3a82b9f823cc0b750b4e45325530"

      define_method(:install) do
        bin.install "shellboto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amiwrpremium/shellboto/releases/download/v0.1.3/shellboto_0.1.3_linux_x86_64.tar.gz"
      sha256 "0d8fb375deebc580f2859a379b1982214aac7685a6b1a70fe2ca9e21fb4d0f32"
      define_method(:install) do
        bin.install "shellboto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amiwrpremium/shellboto/releases/download/v0.1.3/shellboto_0.1.3_linux_arm64.tar.gz"
      sha256 "e74092b0a2415b224c5fd1164c4606c8b8992c55b9ebdac6d685e3bec88a5e45"
      define_method(:install) do
        bin.install "shellboto"
      end
    end
  end

  def caveats
    <<~EOS
      shellboto uses Linux-only syscalls (Credential{Uid}, TIOCGPGRP, flock).
      It builds on macOS but the non-root-shell isolation and the instance
      lock rely on Linux semantics. Supported target is Linux (linuxbrew).

      After install:
        sudo install -d -m 0700 /etc/shellboto
        sudo cp #{opt_prefix}/deploy/env.example         /etc/shellboto/env
        sudo cp #{opt_prefix}/deploy/config.example.toml /etc/shellboto/config.toml
        # Edit both, then:
        shellboto doctor
    EOS
  end

  test do
    assert_match "shellboto", shell_output("#{bin}/shellboto -version")
  end
end
