# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shellboto < Formula
  desc "Telegram bot that gives whitelisted users a live bash shell on the VPS"
  homepage "https://github.com/amiwrpremium/shellboto"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amiwrpremium/shellboto/releases/download/v0.1.1/shellboto_0.1.1_darwin_x86_64.tar.gz"
      sha256 "cc929b6455b288d44141fb3c3cdf34570f81f84f345fb187fab7535a3685023c"

      define_method(:install) do
        bin.install "shellboto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amiwrpremium/shellboto/releases/download/v0.1.1/shellboto_0.1.1_darwin_arm64.tar.gz"
      sha256 "7da8cfcf069f91f38e96f29d9cd2519c5ba0f71e7d63290ddf6d5aa7f70d3e22"

      define_method(:install) do
        bin.install "shellboto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amiwrpremium/shellboto/releases/download/v0.1.1/shellboto_0.1.1_linux_x86_64.tar.gz"
      sha256 "6ecd62f6ac8263e8749d6a0a229254688cf3a5bed615ca432853799b9db64a5c"
      define_method(:install) do
        bin.install "shellboto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amiwrpremium/shellboto/releases/download/v0.1.1/shellboto_0.1.1_linux_arm64.tar.gz"
      sha256 "4b70203ea74bb0f2ca5e781fb0a06ed49c03e1b93c88fb70d01d3789cb475e7d"
      define_method(:install) do
        bin.install "shellboto"
      end
    end
  end

  def caveats
    <<~EOS
      shellboto uses Linux-only syscalls (Credential{Uid}, TIOCGPGRP, flock).
      It builds on macOS but the non-root-shell isolation and the instance
      lock rely on Linux semantics. Supported target is Linux (linuxbrew).

      After install:
        sudo install -d -m 0700 /etc/shellboto
        sudo cp #{opt_prefix}/deploy/env.example         /etc/shellboto/env
        sudo cp #{opt_prefix}/deploy/config.example.toml /etc/shellboto/config.toml
        # Edit both, then:
        shellboto doctor
    EOS
  end

  test do
    assert_match "shellboto", shell_output("#{bin}/shellboto -version")
  end
end
