# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shellboto < Formula
  desc "Telegram bot that gives whitelisted users a live bash shell on the VPS"
  homepage "https://github.com/amiwrpremium/shellboto"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amiwrpremium/shellboto/releases/download/v0.1.0/shellboto_0.1.0_darwin_x86_64.tar.gz"
      sha256 "4dcfd1ecb4f420742f854d9bbf814c9cfd9f11260928aadaf73485650b19c7ca"

      define_method(:install) do
        bin.install "shellboto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amiwrpremium/shellboto/releases/download/v0.1.0/shellboto_0.1.0_darwin_arm64.tar.gz"
      sha256 "7864b5b4e03510edcd96e7eafc9f579acc779fb8fae51ea80537e67d2df42cf9"

      define_method(:install) do
        bin.install "shellboto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amiwrpremium/shellboto/releases/download/v0.1.0/shellboto_0.1.0_linux_x86_64.tar.gz"
      sha256 "c237ac1acd2b9cadaeae4830bf8ca8ec7b11484bb3da616eaab0632330c19a18"
      define_method(:install) do
        bin.install "shellboto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amiwrpremium/shellboto/releases/download/v0.1.0/shellboto_0.1.0_linux_arm64.tar.gz"
      sha256 "93d687211ad2fa1c6d4cd035ef631c3187205327eaa717a31f7a4710b4fe0e6e"
      define_method(:install) do
        bin.install "shellboto"
      end
    end
  end

  def caveats
    <<~EOS
      shellboto uses Linux-only syscalls (Credential{Uid}, TIOCGPGRP, flock).
      It builds on macOS but the non-root-shell isolation and the instance
      lock rely on Linux semantics. Supported target is Linux (linuxbrew).

      After install:
        sudo install -d -m 0700 /etc/shellboto
        sudo cp #{opt_prefix}/deploy/env.example         /etc/shellboto/env
        sudo cp #{opt_prefix}/deploy/config.example.toml /etc/shellboto/config.toml
        # Edit both, then:
        shellboto doctor
    EOS
  end

  test do
    assert_match "shellboto", shell_output("#{bin}/shellboto -version")
  end
end
